# Generated by Django 3.1.4 on 2021-03-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AlterField(
            model_name='agent',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nearby_agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_agencies', to='property_website.agent'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nearby_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_properties', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nearby_schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_schools', to='property_website.school'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nearby_stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_stations', to='property_website.station'),
        ),
        migrations.AlterField(
            model_name='city',
            name='nearby_agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_agencies', to='property_website.agent'),
        ),
        migrations.AlterField(
            model_name='city',
            name='nearby_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_properties', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_area', to='property_website.school'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_area', to='property_website.station'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='property_website.propertytype'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nearby_agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_area_agents', to='property_website.agent'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nearby_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_area_properties', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='station',
            name='nearby_agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_agents', to='property_website.agent'),
        ),
        migrations.AlterField(
            model_name='station',
            name='nearby_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_properties', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_agents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_history', to='property_website.agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='property_website.property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='viewed_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_history', to='property_website.property'),
        ),
    ]
