# Generated by Django 3.1.4 on 2021-03-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_website', '0004_auto_20210312_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='average_increase_last_five_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_increase_last_three_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_increase_last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='estimated_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='estimated_yield_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
